sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 4rcosphere/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 4rcosphere/docker-react npm run test
